/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205746.app;

public class App {
    public static void main(String[] args) {
        String str = null;
        System.out.println(str.length());
        
    }
}
