/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205746.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
